/**
 * Generates a shareable PNG image of the Fix List using canvas.
 * Dark theme card matching the app's visual style.
 * Returns a Blob that can be downloaded or copied to clipboard.
 */

interface FixListCard {
  change: string;
  category: string;
  impact: string;
  reason: string;
  index: number;
}

const COLORS: Record<string, string> = {
  hook: '#fb923c',      // orange-400
  structure: '#60a5fa', // blue-400
  clarity: '#4ade80',   // green-400
  delivery: '#c084fc',  // purple-400
};

const CATEGORY_LABELS: Record<string, string> = {
  hook: 'HOOK',
  structure: 'STRUCTURE',
  clarity: 'CLARITY',
  delivery: 'DELIVERY',
};

export async function generateFixListImage(
  videoTitle: string,
  overallScore: number,
  cards: FixListCard[],
): Promise<Blob> {
  const canvas = document.createElement('canvas');
  const width = 800;
  const cardHeight = 80;
  const headerHeight = 100;
  const footerHeight = 50;
  const padding = 24;
  const height = headerHeight + cards.length * (cardHeight + 12) + footerHeight + padding;

  canvas.width = width * 2; // 2x for retina
  canvas.height = height * 2;
  const ctx = canvas.getContext('2d')!;
  ctx.scale(2, 2);

  // Background
  ctx.fillStyle = '#111111';
  roundRect(ctx, 0, 0, width, height, 16);
  ctx.fill();

  // Header
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 18px -apple-system, system-ui, sans-serif';
  ctx.fillText(truncate(videoTitle, 50), padding, padding + 24);

  // Score badge
  const scoreText = `${Math.round(overallScore)}/100`;
  ctx.font = 'bold 14px -apple-system, system-ui, sans-serif';
  const scoreWidth = ctx.measureText(scoreText).width + 20;
  ctx.fillStyle = '#1e3a5f';
  roundRect(ctx, width - padding - scoreWidth, padding + 6, scoreWidth, 28, 14);
  ctx.fill();
  ctx.fillStyle = '#60a5fa';
  ctx.fillText(scoreText, width - padding - scoreWidth + 10, padding + 24);

  // Subtitle
  ctx.fillStyle = '#6b7280';
  ctx.font = '12px -apple-system, system-ui, sans-serif';
  ctx.fillText('Top changes ranked by expected impact', padding, padding + 48);

  // Divider
  ctx.fillStyle = '#374151';
  ctx.fillRect(padding, headerHeight - 8, width - padding * 2, 1);

  // Cards
  cards.forEach((card, i) => {
    const y = headerHeight + i * (cardHeight + 12);
    const color = COLORS[card.category] || '#9ca3af';

    // Card background
    ctx.fillStyle = '#1a1a1a';
    roundRect(ctx, padding, y, width - padding * 2, cardHeight, 10);
    ctx.fill();

    // Number badge
    ctx.fillStyle = '#2563eb';
    ctx.beginPath();
    ctx.arc(padding + 22, y + 24, 14, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 13px -apple-system, system-ui, sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(String(card.index + 1), padding + 22, y + 28);
    ctx.textAlign = 'left';

    // Category pill
    ctx.fillStyle = color + '20';
    const catLabel = CATEGORY_LABELS[card.category] || card.category.toUpperCase();
    ctx.font = 'bold 9px -apple-system, system-ui, sans-serif';
    const catWidth = ctx.measureText(catLabel).width + 12;
    roundRect(ctx, padding + 44, y + 12, catWidth, 18, 4);
    ctx.fill();
    ctx.fillStyle = color;
    ctx.fillText(catLabel, padding + 50, y + 24);

    // Impact badge
    ctx.font = '9px -apple-system, system-ui, sans-serif';
    ctx.fillStyle = card.impact === 'high' ? '#60a5fa' : '#6b7280';
    const impactText = `↑ ${card.impact === 'high' ? 'High' : 'Medium'} impact`;
    ctx.fillText(impactText, padding + 44 + catWidth + 8, y + 24);

    // Change text
    ctx.fillStyle = '#e5e7eb';
    ctx.font = '12px -apple-system, system-ui, sans-serif';
    ctx.fillText(truncate(card.change, 80), padding + 44, y + 48);

    // Reason
    ctx.fillStyle = '#6b7280';
    ctx.font = '10px -apple-system, system-ui, sans-serif';
    ctx.fillText(truncate(card.reason, 90), padding + 44, y + 66);
  });

  // Footer
  const footerY = height - footerHeight + 8;
  ctx.fillStyle = '#4b5563';
  ctx.font = '10px -apple-system, system-ui, sans-serif';
  ctx.fillText('Generated by Shorta — AI Video Analysis', padding, footerY + 16);

  ctx.fillStyle = '#3b82f6';
  ctx.fillText('shorta.pro', width - padding - ctx.measureText('shorta.pro').width, footerY + 16);

  return new Promise((resolve) => {
    canvas.toBlob((blob) => resolve(blob!), 'image/png');
  });
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

function truncate(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  return text.substring(0, maxLen - 3) + '...';
}

export async function downloadFixListImage(blob: Blob, filename = 'shorta-fix-list.png') {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function copyFixListImage(blob: Blob): Promise<boolean> {
  try {
    await navigator.clipboard.write([
      new ClipboardItem({ 'image/png': blob }),
    ]);
    return true;
  } catch {
    return false;
  }
}
